
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhwtvaqsakxpumamnzgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJod3R2YXFzYWt4cHVtYW1uemdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzI3MjcsImV4cCI6MjA1NTgwODcyN30.5sW7XFeZaTItEF_76UVyW4xpJASOB-DX5Ivr_g1tfgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
